apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: backend:1.0.0
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_APP
          value: "main.py"
        - name: MONGO_URI
          value: "mongodb+srv://admin:Prince050803@cluster0.nhnrnl4.mongodb.net/project_portal?retryWrites=true&w=majority&appName=Cluster0"
        - name: JWT_SECRET_KEY
          value: "team404notfound"
        - name: JWT_ACCESS_TOKEN_EXPIRES
          value: "3600"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
  - port: 5000
    targetPort: 5000
  type: ClusterIP 
  