apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  # Note: These values need to be base64 encoded
  mongodb-uri: bW9uZ29kYitzcnY6Ly9hZG1pbjpQcmluY2UwNTA4MDNAY2x1c3RlcjAubmhucm5sNC5tb25nb2RiLm5ldC9wcm9qZWN0X3BvcnRhbD9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHkmYXBwTmFtZT1DbHVzdGVyMA==
  jwt-secret: dGVhbTQwNG5vdGZvdW5k
  flask-env: cHJvZHVjdGlvbg==  # "production" in base64
  jwt-expires: MzYwMA==  # "3600" in base64 